server:
  port: 8080

debug: false

logging:
  level:
    root: info
    org.mybatis: debug
    org.springframework: info
    org.springframework.jdbc: debug
    com.github.trang: debug
    ${package}: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./samples
    username: root
    password: 123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
    schema: classpath:import.sql